version: 2.1
jobs:
  build-and-test:
    docker:
      - image: 'cimg/openjdk:11.0'
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
          command: echo $MY_ENV
      - run:
          name: Test
          command: mvn clean install
workflows:
  Build and test:
    jobs:
      - build-and-test:
          context:
            - alm_lt
            
